packages:
  - "apps/*"
  - "packages/*"
overrides:
  postcss: 8.5.16
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "esbuild"
  - "msgpackr-extract"
  - "prisma"
  - "sharp"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
